version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r simple-python-app/requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - cd simple-python-app/
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - IMAGE_TAG = "${CODEBUILD_BUILD_ID}"
      - echo IMAGE_TAG
      - docker build -t simple-python-flask-app:$IMAGE_TAG" .
      - docker push "$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:$IMAGE_TAG"
  
  post_build:
    commands:
      - echo "Build completed successfully!"

